import { Profile } from "../Assets";
export const RepoList = [
  {
    id: 1,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 2,
    title: "Ecommerce",
    date: "updated some days ago",
    type: "private",
    language: "javascript",
  },
  {
    id: 3,
    title: "Library",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 4,
    title: "Hospitality",
    date: "updated some days ago",
    type: "private",
    language: "Typscript",
  },
  {
    id: 5,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "Python",
  },
  {
    id: 6,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 7,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 8,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 9,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 10,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 11,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 12,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 13,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 14,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 15,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
  {
    id: 16,
    title: "Pythosalaf repo is here",
    date: "updated some days ago",
    type: "public",
    language: "javascript",
  },
];
